# Site settings
title: RUF | Johnson and Wales University
description: "A minimal blog template, build with Jekyll."
url: "http://rufjwu.github.io"
author:
  name: "Eddie Park"
  email: "epark@ruf.org"
  url: "http://ruf.org"
  
# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

# Plugins
gems: [jekyll-paginate]